import { UserCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { useAuth } from "../context/AuthContext";
import { api } from "../lib/api";

export default function Profile() {
  const { user, profile } = useAuth(); const [results, setResults] = useState([]);
  useEffect(() => { api.myResults().then(setResults); }, [user.uid]);
  return <div className="animate-fade-in"><div className="card flex items-center gap-3 sm:gap-4"><UserCircle className="shrink-0 text-indigo-600" size={48}/><div className="min-w-0"><h1 className="truncate text-xl font-black sm:text-2xl">{profile?.name || user.displayName}</h1><p className="truncate text-sm text-slate-500 sm:text-base">{user.email}</p></div></div><h2 className="mt-6 text-xl font-black sm:mt-8">Natijalar tarixi</h2><div className="mt-4 grid gap-2 sm:hidden">{results.map(r => <div className="card flex items-center justify-between gap-3" key={r.id}><div><p className="font-bold">{r.category}</p><p className="text-xs text-slate-500">{r.correctCount}/25 · {r.percentage}% · {r.level}</p></div><p className="text-xl font-black text-indigo-600">{r.score}</p></div>)}{!results.length && <p className="card text-center text-sm text-slate-500">Hali natija mavjud emas.</p>}</div><div className="card mt-4 hidden overflow-x-auto sm:block"><table className="w-full text-left text-sm"><thead><tr className="border-b dark:border-slate-700"><th className="p-3">Yo'nalish</th><th className="p-3">To'g'ri</th><th className="p-3">Foiz</th><th className="p-3">Ball</th><th className="p-3">Daraja</th></tr></thead><tbody>{results.map(r => <tr className="border-b last:border-0 dark:border-slate-800" key={r.id}><td className="p-3 font-bold">{r.category}</td><td className="p-3">{r.correctCount}/25</td><td className="p-3">{r.percentage}%</td><td className="p-3">{r.score}</td><td className="p-3">{r.level}</td></tr>)}</tbody></table>{!results.length && <p className="p-4 text-center text-slate-500">Hali natija mavjud emas.</p>}</div></div>;
}
